# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "c
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
symbol = " "

[time]
disabled = false
format = '\[$time\]($style) '
time_format = "%T"

[hostname]
ssh_only = false
format =  "[$hostname](bold green) "
disabled = false
